apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-0
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
      pdName: qpidd-persistency-0
      fsType: ext3
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
      pdName: qpidd-persistency-1
      fsType: ext3
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpidd-storage-2
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
      pdName: qpidd-persistency-2
      fsType: ext3
  persistentVolumeReclaimPolicy: Delete
